bin/dumple
`dumple` command ignores the port for mysql database.
=> Pass port to mysqldump in dumple.

lib/geordi/commands/create_database_yml.rb
When you are working on different projects that are using different kinds of databases, I think it would be helpful for the developer to be presented the kind of database he is asked to provide the password for.
=> Show adapter type before asking for the DB password

lib/geordi/db_cleaner.rb
On systems with 10+ CPU cores, applications using `parallel_tests` have databases like `my_project_test12` that are currently not automatically whitelisted by `geordi drop-databases` and would be removed.
This improves the auto-whitelisting accordingly.
=> drop-databases whitelist now includes test databases with multiple digits

lib/geordi/dump_loader.rb
I tried to load a dump in a project using mysql-sandbox and noticed, that it wouldn't accept the host parameter.
=> Add host parameter to mysql dump loader

.gitignore, README.md, lib/geordi/util.rb
"geordi commit" would print a warning "no staged changes" unless new files were staged.
Now it respects **any** staged changes.
=> Fix false "geordi commit" message (closes #83)

.gitignore, lib/geordi/cli.rb
When typing in an unknown geordi command, you got the following deprecation warning with status code 0:
> Deprecation warning: Thor exit with status 0 on errors.
This was fixed by overwriting the `exit_on_failure` method. Now it returns the status code 1.
=> Fix deprecation warning: exit 0 on error (closes #84)

CHANGELOG.md, README.md, features/security_update.feature, features/support/aruba_config.rb, lib/geordi/commands/security_update.rb
Improved the workflow for security-update finish.
Now staging is deployed first, if there is a staging environment.
After that, the user is prompted to check the log and if the application is still running.
If everything is fine, all other stages will be deployed and the user will be prompted again to check the application.
Also added cucumber tests for that and updated the README.
=> Update security-update for improved workflow (closes #89)

.gitignore, CHANGELOG.md, Gemfile.lock, README.md, lib/geordi/commands/commit.rb, lib/geordi/commands/cucumber.rb, lib/geordi/cucumber.rb, lib/geordi/gitpt.rb, lib/geordi/settings.rb, lib/geordi/util.rb, lib/geordi/version.rb
Wrote a settings class which reads from `.geordi.yml` and `~/.config/geordi/global.yml`.  
Updated `geordi commit` to use the new settings, deprecated the old `.pt_project_id` and `~/.gitpt` files.
Added an option to `geordi cucumber` to skip the vnc session via an option in `.geordi.yml`
=> Add helper class for settings and allow disabling vnc (closes #91)

CHANGELOG.md, exe/dumple
In almost all projects we have a capistrano hook to dump the database with dumple during migrations. As dumps might use a lot of disk space it would be nice to have those dumps compressed.
=> add dumple option `--compress` to compress after dumping

README.md, exe/dumple, features/dump.feature, lib/geordi/commands/dump.rb, lib/geordi/remote.rb
In [this issue](https://github.com/makandra/geordi/issues/101) I am explaining the problem of dumple not finding the right key for the database in a database.yml that has multiple databases. So here is a solution where we like to offer another option to define that key.
=> adding an option for supporting multiple databases

.github/workflows/test.yml, CHANGELOG.md, lib/geordi/commands/_setup_vnc.rb, lib/geordi/cucumber.rb
This commit switches from a "no auth" attempt to using a hardcoded
VNC password. This is neccessary to support both vnc4server and
tightvncserver.
The file `lib/geordi/vnc_password.txt` was created using `vncpasswd`
Fixes https://github.com/makandra/geordi/issues/124
=> [#124] Add tightvnc compatibility

CHANGELOG.md, features/dump.feature, lib/geordi/dump_loader.rb
Without this settings, pg_dump tried to import the dump to the database
with the name in the dump and not the one specified in the database.yml.
```
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3043; 0 0 ACL DATABASE some-application_p postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  database "some-application_p" does not exist
Command was: REVOKE CONNECT,TEMPORARY ON DATABASE some-application_p FROM PUBLIC;
GRANT TEMPORARY ON DATABASE some-application_p TO PUBLIC;
GRANT ALL ON DATABASE some-application_p TO some-application_p;
GRANT CONNECT ON DATABASE some-application_p TO icinga;
GRANT CONNECT ON DATABASE some-application_p TO monitoring;
```
=> Ignore ACL when importing a postgres dump

CHANGELOG.md, lib/geordi/commands/console.rb, lib/geordi/commands/shell.rb, lib/geordi/util.rb
`geordi console` will still bundle if it is executed locally.
Gem version detection now works without prior bundling.
Closes #136
=> Remove auto-bundling from geordi shell and geordi console

CHANGELOG.md, features/commit.feature, features/step_definitions/miscellaneous_steps.rb, lib/geordi/gitpt.rb
As discussed [here](https://github.com/makandra/geordi/pull/141#issuecomment-776096374).
=> Allow `geordi commit` to continue if one of the projects is inaccessible

features/cucumber.feature, geordi.gemspec
Resolving issues regarding the post install message string and the cucumber.feature:
- The indentation of the post install message string currently prints two spaces verbatim to the terminal.
- The two spaces should be removed.
- The "should not contain" test in `cucumber.feature:22` is satisfied accidentally if e.g. parallel tests are active but someone changed the output to `> With parallel_tests`.
- They should make a generic expectation or be removed if obsolete.
=> Removed spaces from post install message and clunky console output test.

CHANGELOG.md, Gemfile.lock, geordi.gemspec, lib/geordi/dump_loader.rb
I recently installed geordi 7.0.1 and could not load a dump:
```
geordi dump -l tmp/staging.dump 
Traceback (most recent call last):
11: from ~/.rbenv/versions/2.6.6/bin/geordi:23:in `<main>'
10: from ~/.rbenv/versions/2.6.6/bin/geordi:23:in `load'
9: from ~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/geordi-7.0.1/exe/geordi:7:in `<top (required)>'
8: from ~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/geordi-7.0.1/lib/geordi/util.rb:14:in `installing_missing_gems'
7: from ~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/geordi-7.0.1/exe/geordi:12:in `block in <top (required)>'
6: from ~.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
5: from ~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
4: from …
```
=> make `psych` >= 3.1.0 a runtime dependency to use `YAML.safe_load` with keyword arguments

CHANGELOG.md, README.md, lib/geordi/chromedriver_updater.rb, lib/geordi/commands/chromedriver_update.rb
This command (and `geordi cucumber`/`geordi tests` if the `auto_update_chromedriver` option is active) will now always update to the latest version of chromedriver for the current chrome version.
=> Change update mechanism of `geordi chromedriver-update`

CHANGELOG.md, README.md, features/dump.feature, lib/geordi/commands/dump.rb, lib/geordi/dump_loader.rb
This commit implements dump loading for multiple database environments.
The error message for unsupported database adapters was also improved.
=> [Fix #173] Enable dump loading in multi-database setup

CHANGELOG.md, exe/dumple
In v9.1.0 in noticed that the `geordi dump` command fails in projects that include YAML aliases in the database.yml file:
```
g dump
Unknown alias: test
x Something went wrong.
```
`database.yml`:
```
development:
adapter: postgresql
encoding: unicode
host: 127.0.0.1
database: foo_development
test: &test
adapter: postgresql
encoding: unicode
host: 127.0.0.1
database: foo_test<%= ENV['TEST_ENV_NUMBER']%>
cucumber:
<<: *test
```
In my project Psych `v4.0.1` was used. The load method changed, to use `safe_load` instead.
As the psych version is not fixed in geordi, I added a version switch that can cope with new and old versions.
=> use YAML.safe_load in dumple and allow aliases

exe/b, exe/dumple, lib/geordi/settings.rb, lib/geordi/util.rb
`File.exists?` has been deprecated since Ruby 2.1 and removed in 3.2. It was only an alias for `File.exist?` anyway.
=> Ruby 3.2 compatibility

README.md, lib/geordi/commands/drop_databases.rb, lib/geordi/db_cleaner.rb
These changes would make the `drop-databases` - command just access the postgresql and mysql shells as local user without any password validation. The  changes further assume, that the local user has the required permissions to drop the selected databases. These assumptions are correct for our current setup.
=> Use local user for 'drop-databases' command

README.md, features/console.feature, lib/geordi/commands/console.rb, lib/geordi/commands/delete_dumps.rb, lib/geordi/util.rb
Previously, hitting Ctrl + C in a Rails console started by `geordi console`, the shell would get stuck between bash and console, effectively broken. By using `exec` instead of `system`, this can be fixed without having to implement SIGINT handling in Geordi.
See story #186280123.
=> Improve/fix interrupt handling in locale Rails console

CHANGELOG.md, features/commit.feature, features/step_definitions/miscellaneous_steps.rb, lib/geordi/gitlinear.rb
This change allows `geordi commit` to read the name of the current branch and auto-select an issue that matches the current branch name.
=> Use branch name for geordi commit
